name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx lerna run --stream export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/out
          cname: tokenupgrade.spacechain.com
